# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Litellm add-on
version: "main-latest"
slug: litellm
description: Litellm add-on
url: "https://github.com/dmitriy-b/hass_addons/tree/main/litellm"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/dmitriy-b/{arch}-addon-litellm"
